# https://aka.ms/yaml

trigger:
  - master

variables:
    regression: 1

jobs:
  - job: build_ubuntu
    displayName: Ubuntu
    pool:
      vmImage: 'Ubuntu-22.04'
    timeoutInMinutes: 120
    strategy:
      matrix:
        avx2:
          SIMD: 'AVX2'
          ARCHIVE_NAME: 'avx2'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: Release
        sse2:
          SIMD: 'SSE2'
          ARCHIVE_NAME: 'sse2'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: Release
        avx2_mpi:
          SIMD: 'AVX2'
          ARCHIVE_NAME: 'avx2-mpi'
          STATIC: 0
          MPI: 1
          BUILD_TYPE: RelWithDebInfo
        asan:
          SIMD: 'AVX2'
          ARCHIVE_NAME: 'avx2-asan'
          STATIC: 0
          MPI: 0
          BUILD_TYPE: ASanOpt
    steps:
      - script: |
          sudo apt-get update
          sudo apt-get -y install mpi-default-dev mpi-default-bin
        displayName: Install MPI dependencies
        retryCountOnTaskFailure: "2"
        condition: eq(variables['MPI'], 1)
      - script: |
          mkdir build && cd build
          if [ "${STATIC}" -eq "1" ]; then
              cmake -DCMAKE_INSTALL_PREFIX=${BUILD_SOURCESDIRECTORY}/hhsuite \
                    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                    -DBUILD_SHARED_LIBS=OFF \
                    -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
                    -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
                    -DHAVE_${SIMD}=1 \
                    -DCHECK_MPI=${MPI} \
                    ..
          else
              cmake -DCMAKE_INSTALL_PREFIX=${BUILD_SOURCESDIRECTORY}/hhsuite \
                    -DENABLE_SANITIZERS=1 \
                    -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                    -DHAVE_${SIMD}=1 \
                    -DCHECK_MPI=${MPI} \
                    ..
          fi
          make -j $(nproc --all)
          make install
          cd ${BUILD_SOURCESDIRECTORY}
          cp LICENSE README.md hhsuite
          tar -czvf hhsuite-linux-${ARCHIVE_NAME}.tar.gz hhsuite
        displayName: Build HHsuite
      - script: |
          if [ "${BUILD_TYPE}" = "ASanOpt" ]; then
              echo "leak:libgomp.so.1" > ${BUILD_SOURCESDIRECTORY}/LSan.supp
              export LSAN_OPTIONS=suppressions=${BUILD_SOURCESDIRECTORY}/LSan.supp
          fi
          export OMPI_MCA_rmaps_base_oversubscribe=1
          cd ${BUILD_SOURCESDIRECTORY}/data
          PATH="${BUILD_SOURCESDIRECTORY}/hhsuite/bin:$PATH"
          ./test.sh
        displayName: Run regression
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/hhsuite-linux-$(ARCHIVE_NAME).tar.gz
          artifactName: hhsuite-linux-$(ARCHIVE_NAME)
        condition: eq(variables['STATIC'], 1)

  - job: build_ubuntu_cross
    displayName: Ubuntu Cross-Compile
    pool:
      vmImage: 'Ubuntu-22.04'
    timeoutInMinutes: 120
    strategy:
      matrix:
        power8:
          SIMD: POWER8
          ARCH: ppc64el
          ARCHIVE_NAME: ppc64el-power8
          CPREF: powerpc64le
        power9:
          SIMD: POWER9
          ARCH: ppc64el
          ARCHIVE_NAME: ppc64el-power9
          CPREF: powerpc64le
        arm64:
          SIMD: ARM8
          ARCH: arm64
          ARCHIVE_NAME: arm64
          CPREF: aarch64
    steps:
      - script: |
          CODENAME=$(lsb_release -cs)
          sudo dpkg --add-architecture "$ARCH"
          cat << HEREDOC | sudo tee /etc/apt/sources.list
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${CODENAME} main universe multiverse
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${CODENAME}-updates main universe multiverse
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ ${CODENAME}-backports main universe multiverse
          deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ ${CODENAME}-security main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME} main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME}-updates main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME}-backports main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ ${CODENAME}-security main universe multiverse
          HEREDOC
          sudo apt-get update
          sudo apt-get -y install -o APT::Immediate-Configure=false crossbuild-essential-$ARCH qemu-user-static
        retryCountOnTaskFailure: "2"
        displayName: Install crossbuild toolchain
      - script: |
          mkdir build && cd build
          CC=${CPREF}-linux-gnu-gcc CXX=${CPREF}-linux-gnu-g++ \
          cmake -DCMAKE_INSTALL_PREFIX=${BUILD_SOURCESDIRECTORY}/hhsuite \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
            -DHAVE_${SIMD}=1 \
            -DCHECK_MPI=0 \
            ..
          make -j $(nproc --all)
          make install
          cd ${BUILD_SOURCESDIRECTORY}
          cp LICENSE README.md hhsuite
          tar -czvf hhsuite-linux-${ARCHIVE_NAME}.tar.gz hhsuite
        displayName: Build HHsuite
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}/data
          PATH="${BUILD_SOURCESDIRECTORY}/hhsuite/bin:$PATH"
          ./test.sh
        displayName: Run regression in QEMU
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/hhsuite-linux-$(ARCHIVE_NAME).tar.gz
          artifactName: hhsuite-linux-$(ARCHIVE_NAME)

  - job: build_macos
    displayName: macOS
    pool:
      vmImage: 'macos-latest'
    steps:
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}
          ./scripts/build_darwin_universal.sh . build_osx
          cp ${BUILD_SOURCESDIRECTORY}/LICENSE ${BUILD_SOURCESDIRECTORY}/README.md ${BUILD_SOURCESDIRECTORY}/build_osx/hhsuite/
          tar -czvf ${BUILD_SOURCESDIRECTORY}/hhsuite-osx-universal.tar.gz -C ${BUILD_SOURCESDIRECTORY}/build_osx hhsuite
        displayName: Build HHsuite
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}/data
          PATH="${BUILD_SOURCESDIRECTORY}/build_osx/hhsuite/bin:$PATH"
          ./test.sh
        displayName: Run regression
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/hhsuite-osx-universal.tar.gz
          artifactName: hhsuite-osx-universal

  - job: upload_artifacts
    displayName: Upload Artifacts
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn:
      - build_macos
      - build_ubuntu
      - build_ubuntu_cross
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@1
        inputs:
          targetPath: $(Build.SourcesDirectory)
      - task: DownloadSecureFile@1
        inputs:
          secureFile: secretKeyPleaseDontSteal
        displayName: Get Deployment Key
      - script: |
          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
          ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
          cd "${BUILD_SOURCESDIRECTORY}"
          mv hhsuite-*/hhsuite-*.tar.gz .
          set --
          for FILE in hhsuite-*.tar.gz; do
            ssh-keygen -Y sign -f ~/.ssh/id_rsa -n file "${FILE}"
            set -- "$@" -F "file[]=@${FILE}" -F "signature[]=@${FILE}.sig"
          done
          curl --fail --retry 5 --retry-all-errors -X POST "$@" \
            -F identifier="hhsuite" -F directory="${BUILD_SOURCEVERSION}" \
              https://mmseqs.com/upload
        displayName: Upload
